### ISSUE TITLE
Empty array of layers in screen method

### ISSUE THREAD

**Issue by kubiqsk** [zeplin/zeplin-extension-documentation#38]
There are no layers listed in the array in screen function:
```
function screen( context, selectedVersion, selectedScreen ){
	return {
		code: JSON.stringify( selectedVersion.layers, null, 2 ),
		language: "json"
	};
}
```
This will return always empty array []
How should I go through all layers in screen?

**Comment by kubiqsk** [comment]
There are no layers listed in the array in screen function:
```
function screen( context, selectedVersion, selectedScreen ){
	return {
		code: JSON.stringify( selectedVersion.layers, null, 2 );,
		language: "json"
	};
}
```
This will return always empty array []
How should I go through all layers in screen?

**Comment by dirtybit** [comment]
`JSON.stringify` is not able to handle circular structures in objects, that's why you see empty array even though layers list is not empty. You can try using something similar to [`flatted`](https://www.npmjs.com/package/flatted) to get JSON representation of objects with circular references. 

That said, being not able to use JSON.stringify on extensions model objects due to the circular references is something we'd love to fix. It really hurts the experience of extension developers, I hope it'll be fixed soon.

**Comment by kubiqsk** [comment]
Hello,
ok, thank you, now I get it ;)

I'm trying to create extension, that will export all texts - very helpful for web developers when bulk creating content on web - this is my code:

`
function screen( context, selectedVersion, selectedScreen ){
	var texts = "";

	selectedVersion.layers.forEach(function( layer ){
		if( layer.type == "text" ){
			texts += layer.content + "\n---\n";
		}
	});

	return {
		code: texts,
		language: "text"
	};
}

export default {
	screen
};
`

Problem is that there is nothing on the first load in selectedVersion.layers, but after I go to another screen and then back, then there is expected content. Can you tell me, why selectedVersion.layers is empty after open screen, is there some memory that needs to be loaded firstly?

**Comment by dirtybit** [comment]
Hi @kubiqsk,

This was happening because of an issue in the app. It's been fixed, so it should be working fine now. 

Please let us know if you have any other issues.

**Comment by kubiqsk** [comment]
Thanks, it works in desktop app, but I still experience same issue on web app.
I have also one more question, I'm trying to create options for text separator so options is type: text and I want to set default value to "\n----\n" but of course I need to escape \n so I've tried \\n and \\\n and \\\\n and all of them do something different in desktop app and something else in web app :D
