### ISSUE TITLE
Refused to connect to * because it violates the following Content Security Policy directive: "connect-src 'self'.

### ISSUE THREAD

**Issue by jozsefmezei** [zeplin/zeplin-extension-documentation#55]
I open my zeplin project in a browser and I got this error in the console:
 1. Refused to connect to 'https://firebaselogging-pa.googleapis.com/v1/firelog/legacy/*****' 
because it violates the following Content Security Policy directive: "connect-src 'self' 
https://*.facebook.com https://*.g.doubleclick.net https://*.google-analytics.com https://*.intercom.io 
https://*.mixpanel.com https://*.nr-data.net https://*.pusher.com https://*.stripe.com https://*.zeplin.io 
wss://*.intercom.io wss://*.pusher.com"

2. I try to add my local extension and got a similar error:  
﻿﻿[Report Only] Refused to connect to 'http://127.0.0.1:7070/manifest.json' because it violates the following Content Security Policy directive: "connect-src 'self' https://*.facebook.com https://*.g.doubleclick.net https://*.google-analytics.com https://*.intercom.io https://*.mixpanel.com https://*.nr-data.net https://*.pusher.com https://*.stripe.com https://*.zeplin.io wss://*.intercom.io wss://*.pusher.com".

I can add my local extension, but it doesn't work. Zeplin shows this message to me: **Fetching extension failed** and the console has the same error again.

**Comment by ergunsh** [comment]
Hey Jozsef,

There was an issue with adding local extensions in our Windows and Web apps. We've released the fix and the issue must be resolved now.

**Comment by haikyuu** [comment]
Still happening in Zeplin desktop on mac as well as safari mac
